Resume/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
from django.contrib import staticfiles 

urlpatterns = [
    path('', include('about.urls', namespace='about')),
    path('experience/', include('experience.urls', namespace='experience')),
    path('education/', include('education.urls', namespace='education')),
    path('skills/', include('skills.urls', namespace='skills')),
    path('interests/', include('interests.urls', namespace='interests')),
    path('awards/', include('awards.urls', namespace='awards')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('', views.about, name='about')
]

awards/urls.py
from django.urls import path
from . import views

app_name = 'awards'

urlpatterns = [
    path('', views.awards, name='awards')
]

education/urls.py
from django.urls import path
from . import views

app_name = 'education'

urlpatterns = [
    path('', views.education, name='education')
]

experience/urls.py
from django.urls import path
from . import views


app_name = 'experience'

urlpatterns = [
    path('', views.experience, name='experience')
]

interests/urls.py
from django.urls import path
from . import views

app_name = 'interests'

urlpatterns = [
    path('', views.interests, name='interests')
]

skills/urls.py
from django.urls import path
from . import views

app_name = 'skills'

urlpatterns = [
    path('', views.skills, name='skills')
]

about/models.py
from django.db import models

# Create your models here.

awards/models.py
from django.db import models

# Create your models here.

education/models.py
from django.db import models

# Create your models here.

experience/models.py
from django.db import models

# Create your models here.

interests/models.py
from django.db import models

# Create your models here.

skills/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render


def about(request):
    context = {}
    template = 'about/about.html'
    return render(request, template, context)

awards/views.py
from django.shortcuts import render


def awards(request):
    context = {}
    template = 'awards/awards.html'
    return render(request, template, context)

education/views.py
from django.shortcuts import render


def education(request):
    context = {}
    template = 'education/education.html'
    return render(request, template, context)

experience/views.py
from django.shortcuts import render


def experience(request):
    context = {}
    template = 'experience/experience.html'
    return render(request, template, context)

interests/views.py
from django.shortcuts import render


def interests(request):
    context = {}
    template = 'interests/interests.html'
    return render(request, template, context)

skills/views.py
from django.shortcuts import render


def skills(request):
    context = {}
    template = 'skills/skills.html'
    return render(request, template, context)

about/templates/about/about.html
{% extends 'base.html' %}

{% load static %}

{% block title %}About{% endblock %}

{% block content %}
     <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
        <div class="my-auto">
          <h1 class="mb-0">Hang
            <span class="text-primary">XU</span>
          </h1>
          <div class="subheading mb-5">The Hong Kong University of Science and Technology. Clear Water Bay, Kowloon, Hong Kong
            <a href="mailto:hxubf@connect.ust.hk">hxubf@connect.ust.hk</a>
          </div>
          <p class="mb-5">I will study and live in HKUST during my Phd period.My major is software engineering.I have another home named CASTLE.I hope that I will have some memorable experience there.</p>
          <!-- <ul class="list-inline list-social-icons mb-0">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul> -->
        </div>
      </section>

{% endblock %}

awards/templates/awards/awards.html
{% extends 'base.html' %}


{% block title %}Awards{% endblock %}


{% block content %}


    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="awards">
        <div class="my-auto">
          <h2 class="mb-5">Awards &amp; Certifications</h2>
          <ul class="fa-ul mb-0">
            <li>
              <i class="fa-li fa fa-trophy text-warning"></i>
              Huawei Phd Fellowship</li>
            <li>
              <i class="fa-li fa fa-trophy text-warning"></i>
              Outstanding graduate</li>
              <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                National Scholarship 2014, 2015, 2016</li> 
            <!-- <li>
              <i class="fa-li fa fa-trophy text-warning"></i>
              1<sup>st</sup>
              Place - University of Colorado Boulder - Emerging Tech Competition 2009</li>
            <li>
              <i class="fa-li fa fa-trophy text-warning"></i>
              1<sup>st</sup>
              Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)</li>
            <li>
              <i class="fa-li fa fa-trophy text-warning"></i>
              2<sup>nd</sup>
              Place - University of Colorado Boulder - Emerging Tech Competition 2008</li>
            <li>
            <li>
              <i class="fa-li fa fa-trophy text-warning"></i>
              1<sup>st</sup>
              Place - James Buchanan High School - Hackathon 2006</li>
            <li>
              <i class="fa-li fa fa-trophy text-warning"></i>
              3<sup>rd</sup>
              Place - James Buchanan High School - Hackathon 2005</li> -->
          </ul>
        </div>
      </section>
{% endblock %}

education/templates/education/education.html
{% extends 'base.html' %}


{% block title %}Education{% endblock %}

{% block content %}


      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="education">
        <div class="my-auto">
          <h2 class="mb-5">Education</h2>

          <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">The Hong kong University of Science and Technology </h3>
              <div class="subheading mb-3">Phd, Software Engineering</div>
              <!-- <div>Computer Science - Web Development Track</div>
              <p>GPA: 3.23</p> -->
            </div>
            <div class="resume-date text-md-left">
              <span class="text-primary">August 2018 - </span>
            </div>
          </div>

          <div class="resume-item d-flex flex-column flex-md-row">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">Wuhan University</h3>
              <div class="subheading mb-3">Bachelor, Software Engineering</div>
              <p>GPA: 3.83</p>
            </div>
            <div class="resume-date text-md-left">
              <span class="text-primary">September 2013 - June 2017</span>
            </div>
          </div>

        </div>
      </section>

{% endblock %}

experience/templates/experience/experience.html
{% extends 'base.html' %}


{% block title %}Experience{% endblock %}

{% block content %}

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
        <div class="my-auto">
          <h2 class="mb-5">Experience</h2>

          <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">Research assistant, Nvidia Research Center, Wuhan University</h3>
              <div class="subheading mb-3">classification of maxillofacial tumors</div>
              <p>Project Objective: To develop a system which can recognize classification of maxillofacial tumors, which could help pathologists improve diagnosis rate of tumors.</p>
              <p>My main task is tou use the SVM, decision tree, BP neural network and convolutional neural network respectively for image classification.</p>
              <p>Optimize the parameters in order to improve the classification accuracy.</p>
            </div>
            <div class="resume-date text-md-right">
              <span class="text-primary">December 2016 - June 2017</span>
            </div>
          </div>

          <!-- <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">Web Developer</h3>
              <div class="subheading mb-3">Intelitec Solutions</div>
              <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.</p>
            </div>
            <div class="resume-date text-md-right">
              <span class="text-primary">December 2011 - March 2013</span>
            </div>
          </div>

          <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">Junior Web Designer</h3>
              <div class="subheading mb-3">Shout! Media Productions</div>
              <p>Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.</p>
            </div>
            <div class="resume-date text-md-right">
              <span class="text-primary">July 2010 - December 2011</span>
            </div>
          </div>

          <div class="resume-item d-flex flex-column flex-md-row">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">Web Design Intern</h3>
              <div class="subheading mb-3">Shout! Media Productions</div>
              <p>Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.</p>
            </div>
            <div class="resume-date text-md-right">
              <span class="text-primary">September 2008 - June 2010</span>
            </div>
          </div>

        </div> -->
      </section>
{% endblock %}

interests/templates/interests/interests.html
{% extends 'base.html' %}


{% block title %}Interests{% endblock %}

{% block content %}
          <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="interests">
        <div class="my-auto">
          <h2 class="mb-5">Interests</h2>
          <p>Apart from being a phd student, I enjoy most of my time being outdoors. I like playing basketball, mountain biking, enjoying food, and jogging.</p>
          <p class="mb-0">When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows, and I spend a large amount of my free time exploring the latest technolgy advancements in the coding world.</p>
        </div>
      </section>
{% endblock %}

skills/templates/skills/skills.html
{% extends 'base.html' %}


{% block title %}Skills{% endblock %}

{% block content %}
      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="skills">
        <div class="my-auto">
          <h2 class="mb-5">Skills</h2>

          <div class="subheading mb-3">Programming Languages &amp; Tools</div>
          <ul class="list-inline list-icons">
            <li class="list-inline-item">
              <i class="devicons devicons-python"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-java"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-django"></i>
            </li>
            <!-- <li class="list-inline-item">
              <i class="devicons devicons-jquery"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-sass"></i>
            </li> -->
            <li class="list-inline-item">
              <i class="devicons devicons-ubuntu"></i>
            </li>
            <!-- <li class="list-inline-item">
              <i class="devicons devicons-bootstrap"></i>
            </li> -->
            <!-- <li class="list-inline-item">
              <i class="devicons devicons-wordpress"></i>
            </li> -->
            <!-- <li class="list-inline-item">
              <i class="devicons devicons-grunt"></i>
            </li> -->
            <!-- <li class="list-inline-item">
              <i class="devicons devicons-css"></i>
            </li> -->
            <li class="list-inline-item">
              <i class="devicons devicons-html5"></i>
            </li>
          </ul>

          <div class="subheading mb-3">Workflow</div>
          <ul class="fa-ul mb-0">
            <li>
              <i class="fa-li fa fa-check"></i>
              Research</li>
            <li>
              <i class="fa-li fa fa-check"></i>
              Design</li>
            <li>
              <i class="fa-li fa fa-check"></i>
              Implement</li>
            <li>
              <i class="fa-li fa fa-check"></i>
              Debugging</li>
          </ul>
        </div>
      </section>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Resume | {% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/devicons/css/devicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/resume.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'about:about' %}">
        <span class="d-block d-lg-none">Resume</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'img/profile.jpg' %}" alt="">
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      {% block navbar %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'about:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'experience:experience' %}">Experience</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'education:education' %}">Education</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'skills:skills' %}">Skills</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'interests:interests' %}">Interests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'awards:awards' %}">Awards</a>
          </li>
        </ul>
      </div>
    </nav>
    {% endblock %}


    <div class="container-fluid p-0">
 {% block content %}
 {% endblock %}
    </div>


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/resume.min.js' %}"></script>

  </body>

</html>